import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>terminalState</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/code.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-normal">
          Welcome to the space of Million Coders
        </h1>
      </main>
    </div>
  );
};

export default Home;
