import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { AxiosResponse } from "axios";

// other components / instances
import { fetchCategories } from "../http";
import { ICategory, ICollectionResponse } from "../types";

interface IPropType {
  categories: {
    items: ICategory[];
  };
}

const Home: NextPage<IPropType> = ({ categories }) => {
  console.log("Categories", categories);
  return (
    <div>
      <Head>
        <title>terminalState</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/code.ico" />
      </Head>

      {categories.items.map((category) => {
        return <span key={category.id}>{category.attributes.Title}</span>;
      })}

      <main>
        <h1 className="text-3xl font-normal">
          Welcome to the space of Million Coders
        </h1>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> =
    await fetchCategories();
  console.log("Categories", categories);
  return {
    props: {
      categories: {
        items: categories.data,
      },
    },
  };
};

export default Home;
